### PR TITLE
version updates

### PR DESCRIPTION
**Pull request by runtologist**
* bump ZIO to RC10-1
* re-add tests
* build for Scala 2.13

### CODE REVIEW

**Comment by kaishh** [comment]
@runtologist 
Thank you very much for adding more tests 🙏 
Is this PR ready for review/merge, since it's passing on CI?

**Comment by runtologist** [comment]
@kaishh I've just added the tests again I wrote before the interops were moved out of the code repo. ;-) Somehow they got lost.

Now it's ready. I've also added a 2.13 build for Circle CI.

The only thing missing is making `test213_jvm_jdk8` a required check. No clue how to do that. I guess that needs to be configured in Github?

**Comment by kaishh** [comment]
@runtologist Nope, circle config is entirely in that yaml, fairly sure adding a 2.13 job [here](https://github.com/zio/interop-reactive-streams/blob/master/.circleci/config.yml#L77) will spawn it for all builds. Thanks again!

**Comment by runtologist** [comment]
@kaishh The build it is spawned, but if you "Show all checks", it is not labeled as Required. I assue that means it is allowed to fail.

**Comment by kaishh** [comment]
@runtologist Hmm, I actually don't know what does `Required` mean... I highly suspect no one changed github settings for `zio` or `interop-cats` repos, yet 213 checks show up as `Required` in new PRs – may be GH doesn't label checks that appeared in PR itself, not on master, as Required?

**Comment by runtologist** [comment]
OK, seems to work then, thx.

**Comment by runtologist** [comment]
review anyone? 👋

**Comment by kaishh** [comment]
@runtologist I thought you'd merge since you have commit rights :D

**Comment by runtologist** [comment]
But I can't self-approve. ;-)

**Comment by kaishh** [comment]
@runtologist 
Do you want to cut a new release yourself (https://github.com/zio/interop-reactive-streams/releases -> 'Draft a new release', probably `1.0.2.1-RC1`?) or do you want someone else to do it?

**Comment by runtologist** [comment]
I'll cut it myself.

**Comment by kaishh** [comment]
@runtologist 
Description here- https://github.com/zio/interop-cats/issues/1#issuecomment-505616709
So, first 3 numbers should be the same as the version of project under interop – for API changes we're supposed to move the last number...

**Pull request merged**
