### PR TITLE
Update Introduction Section

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Review by runtologist — APPROVED** [review]

**Comment by khajavi** [comment]
@runtologist I'm ready for merge it.

**Comment by runtologist** [comment]
Compilation on Scala 3 fails after the version bump. This needs to be reverted before we can merge. Compilation should be fixed in a separate PR.

**Comment by khajavi** [comment]
@runtologist 
It seems the failure of this PR is not related to the work that I've done. Try to run `sbt ++3.1.0 publishLocal` on the `master` branch.

**Comment by khajavi** [comment]
@runtologist Hey Simon, could you please take a look? It is ready for your review.

**Pull request merged**
