### PR TITLE
Fix ZStream From Pull Implementation

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by runtologist** [comment]
Do I understand correctly that fromPull is only needed temporarily until the fix lands in ZIO streams?

**Comment by adamgfraser** [comment]
Correct. I just inlined the code from the latest version of the `series/2.x` branch so once we do the next release we can delete it.

**Review by runtologist — APPROVED** [review]
LGTM. Thank you for fixing this in ZIO streams.

**Comment by adamgfraser** [comment]
You want to do a release?

**Pull request merged**
