### PR TITLE
fix race in Adapters.publisherToStream

### LINKED ISSUE #338: Adapters.publisherToStream doesn't emit all messages
```scala
ZIO
  .foreach((1 to 10000).toList)(_ =>
    Adapters
      .publisherToStream(new NumberIterablePublisher(0, 1, executor), 16)
      .runCount
  )
  .map(_.count(_ == 1)) // returns 9995
```
Version: 2.0.0

it looks like between [read buffer](https://github.com/zio/interop-reactive-streams/blob/b5167496b8ecb233fbf80b6ddcbdecf01e53ba67/src/main/scala/zio/interop/reactivestreams/Adapters.scala#L99) and [start await](https://github.com/zio/interop-reactive-streams/blob/b5167496b8ecb233fbf80b6ddcbdecf01e53ba67/src/main/scala/zio/interop/reactivestreams/Adapters.scala#L102), subscriber receives message and complete signal. 
In the await method, it sees that 'done' variable is defined and [stops the stream](https://github.com/zio/interop-reactive-streams/blob/b5167496b8ecb233fbf80b6ddcbdecf01e53ba67/src/main/scala/zio/interop/reactivestreams/Adapters.scala#L152),  skipping received message

### PR DESCRIPTION
**Pull request by darl**
fixes #338

### CODE REVIEW

**Review by runtologist — COMMENTED** [review]
Good catch!

Shouldn't we wait for the queue to empty and then fail with `value` in order to not swallow the error?

**Comment by darl** [comment]
> Shouldn't we wait for the queue to empty and then fail with value in order to not swallow the error?

I think error stored in field `done`.
`await` will be called on next iteration and return stored error
https://github.com/zio/interop-reactive-streams/blob/71956699fe082beb6e11bb50a961bbbadaa118c7/src/main/scala/zio/interop/reactivestreams/Adapters.scala#L102

**Comment by evis** [comment]
@runtologist PTAL

**Comment by evis** [comment]
@runtologist PTAL

**Review by runtologist — APPROVED** [review]

**Comment by runtologist** [comment]
@darl @evis Thank you for catching and fixing this!

**Pull request merged**
